// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const SQUARE_COUNTER = 'SQUARE_COUNTER'
export const CUBE_COUNTER = 'CUBE_COUNTER';
export const COUNTER_1000 = 'COUNTER_1000';